<?php

namespace App\Repositories;

use Illuminate\Support\Facades\Log;

class UserEloquentRepository extends EloquentRepository
{

    protected function prepareAttributes($request = null): array
    {
        return $request->toArray();
    }

    public function find(callable $getModel, array $identifier, null|\Illuminate\Contracts\Auth\Authenticatable|\App\User $user = null): mixed
    {
        Log::info('UsersEloquentRepository@find: ' . implode(',' , $identifier) . ' user: ' . $user);
        return parent::find($getModel, $identifier, $user); // TODO: Change the autogenerated stub
    }
}